#!/bin/bash
IP=192.168.1.3
PORT=22345
ifconfig br0 192.168.1.2
export LD_LIBRARY_PATH=/data/cay:$LD_LIBRARY_PATH
echo "$LD_LIBRARY_PATH"
/data/cay/socat -d  /dev/ttyS1,nonblock,raw,ixon=1,opost=0,cs8,b57600,parenb=0,cstopb=0,clocal=1,cread=1,crtscts=0,icanon=0,echo=0,iexten=0,isig=0,  tcp:$IP:$PORT
#!/bin/bash
IP=192.168.1.3
PORT=22345
export LD_LIBRARY_PATH=/data/cay:$LD_LIBRARY_PATH
echo "$LD_LIBRARY_PATH"
/data/cay/socat -d  /dev/ttyS1,nonblock,raw,ixon=1,opost=0,cs8,b57600,parenb=0,cstopb=0,clocal=1,cread=1,crtscts=0,icanon=0,echo=0,iexten=0,isig=0,  tcp:$IP:$PORT
